services:
  - type: web
    name: fbl-voting-website
    env: node
    plan: starter
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:/mnt/data/prisma/dev.db
      - key: PERSISTENT_DISK_PATH
        value: /mnt/data
    disk:
      name: fbl-voting-data
      mountPath: /mnt/data
      sizeGB: 1

